// Regenerates site/firmware.js from the built firmware binaries.
// Usage: node tools/make_firmware.mjs
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';

const root = fileURLToPath(new URL('..', import.meta.url));
const firmwares = [
    // network
    ['eth_http', 'firmware/eth_http/eth_http.bin', 'eth_http.bin'],
    ['eth_dhcp', 'firmware/eth_dhcp/eth_dhcp.bin', 'eth_dhcp.bin'],
    ['eth_test', 'firmware/eth_test/eth_test.bin', 'eth_test.bin'],
    ['eth_http_f429', 'firmware/eth_http/eth_http_f429.bin', 'eth_http_f429.bin'],
    ['eth_dhcp_f429', 'firmware/eth_dhcp/eth_dhcp_f429.bin', 'eth_dhcp_f429.bin'],
    ['eth_test_f429', 'firmware/eth_test/eth_test_f429.bin', 'eth_test_f429.bin'],
    ['eth_feat_test', 'firmware/eth_feat_test/eth_feat_test.bin', 'eth_feat_test.bin'],
    ['eth_feat_test_f429', 'firmware/eth_feat_test/eth_feat_test_f429.bin', 'eth_feat_test_f429.bin'],
    ['eth_adv', 'firmware/eth_adv/eth_adv.bin', 'eth_adv.bin'],
    ['eth_adv_f429', 'firmware/eth_adv/eth_adv_f429.bin', 'eth_adv_f429.bin'],
    ['lwip_demo', 'firmware/lwip_demo/lwip_demo.bin', 'lwip_demo.bin'],
    ['lwip_demo_f429', 'firmware/lwip_demo/lwip_demo_f429.bin', 'lwip_demo_f429.bin'],
    ['eth_irq_test_f429', 'firmware/eth_irq_test/eth_irq_test_f429.bin', 'eth_irq_test_f429.bin'],
    // bare-metal demos
    ['blinky', 'firmware/blinky/blinky.bin', 'blinky.bin'],
    // board variants (own link scripts/sizes/LEDs; VE/ZE share the stock bin)
    ['blinky_f401', 'firmware/blinky_f401/blinky_f401.bin', 'blinky_f401.bin'],
    ['blinky_f411', 'firmware/blinky_f411/blinky_f411.bin', 'blinky_f411.bin'],
    ['blinky_f407g', 'firmware/blinky_f407g/blinky_f407g.bin', 'blinky_f407g.bin'],
    ['blinky_nucleo_f401', 'firmware/blinky_nucleo_f401/blinky_nucleo_f401.bin', 'blinky_nucleo_f401.bin'],
    ['blinky_nucleo_f411', 'firmware/blinky_nucleo_f411/blinky_nucleo_f411.bin', 'blinky_nucleo_f411.bin'],
    ['blinky_f429', 'firmware/blinky_f429/blinky_f429.bin', 'blinky_f429.bin'],
    ['blinky_f407ve', 'firmware/blinky/blinky.bin', 'blinky.bin'],
    ['blinky_f407ze', 'firmware/blinky/blinky.bin', 'blinky.bin'],
    // Arduino per-board validation (same sketch, 8 targets — Serial prints +
    // LED blink + SysTick delay; see site/test_arduino_boards.mjs)
    ['arduino_bp_f401cc', 'firmware/arduino_board/build-bp_f401cc/arduino_board.ino.bin', 'arduino_bp_f401cc.bin'],
    ['arduino_bp_f411ce', 'firmware/arduino_board/build-bp_f411ce/arduino_board.ino.bin', 'arduino_bp_f411ce.bin'],
    ['arduino_nucleo_f401re', 'firmware/arduino_board/build-nucleo_f401re/arduino_board.ino.bin', 'arduino_nucleo_f401re.bin'],
    ['arduino_nucleo_f411re', 'firmware/arduino_board/build-nucleo_f411re/arduino_board.ino.bin', 'arduino_nucleo_f411re.bin'],
    ['arduino_disco_f407vg', 'firmware/arduino_board/build-disco_f407vg/arduino_board.ino.bin', 'arduino_disco_f407vg.bin'],
    ['arduino_disco_f429zi', 'firmware/arduino_board/build-disco_f429zi/arduino_board.ino.bin', 'arduino_disco_f429zi.bin'],
    ['arduino_black_f407ve', 'firmware/arduino_board/build-black_f407ve/arduino_board.ino.bin', 'arduino_black_f407ve.bin'],
    ['arduino_black_f407ze', 'firmware/arduino_board/build-black_f407ze/arduino_board.ino.bin', 'arduino_black_f407ze.bin'],
    // host-driven / OS showcases (need IRQs and/or JS devices; see app.js)
    ['exti_test', 'firmware/exti_test/exti_test.bin', 'exti_test.bin'],
    ['flash_test', 'firmware/flash_test/flash_test.bin', 'flash_test.bin'],
    ['spi_flash_test', 'firmware/spi_flash_test/spi_flash_test.bin', 'spi_flash_test.bin'],
    ['freertos_test', 'firmware/freertos_test/freertos_test.bin', 'freertos_test.bin'],
    // demo firmwares (new peripheral showcases)
    ['adc_demo', 'firmware/adc_demo/adc_demo.bin', 'adc_demo.bin'],
    ['dac_demo', 'firmware/dac_demo/dac_demo.bin', 'dac_demo.bin'],
    ['pwm_demo', 'firmware/pwm_demo/pwm_demo.bin', 'pwm_demo.bin'],
    // test binaries (boot + print on UART; see site/probe_firmwares.mjs)
    ['hal_test', 'firmware/hal_test/hal_test.ino.bin', 'hal_test.ino.bin'],
    ['crypto_test', 'firmware/crypto_test/build/crypto_test.ino.bin', 'crypto_test.ino.bin'],
    ['crypto_deep_test', 'firmware/crypto_deep_test/crypto_deep_test.bin', 'crypto_deep_test.bin'],
    ['rx_crypto_test', 'firmware/rx_crypto_test/rx_crypto_test.bin', 'rx_crypto_test.bin'],
    ['periph_test', 'firmware/periph_test/periph_test.ino.bin', 'periph_test.ino.bin'],
    ['new_periph_test', 'firmware/new_periph_test/new_periph_test.ino.bin', 'new_periph_test.ino.bin'],
    ['deep_periph_test', 'firmware/deep_periph_test/build/deep_periph_test.ino.bin', 'deep_periph_test.ino.bin'],
    ['comprehensive_test', 'firmware/comprehensive_test/comprehensive_test.bin', 'comprehensive_test.bin'],
    ['eth_irq_test', 'firmware/eth_irq_test/eth_irq_test.bin', 'eth_irq_test.bin'],
    ['edge_test', 'firmware/edge_test/edge_test.ino.bin', 'edge_test.ino.bin'],
    ['echo_test', 'firmware/echo_test/build/echo_test.ino.bin', 'echo_test.ino.bin'],
    ['rx_interrupt_test', 'firmware/rx_interrupt_test/rx_interrupt_test.bin', 'rx_interrupt_test.bin'],
    ['rx_interrupt_test_f401', 'firmware/rx_interrupt_test/rx_interrupt_test_f401.bin', 'rx_interrupt_test_f401.bin'],
    ['rx_interrupt_test_f411', 'firmware/rx_interrupt_test/rx_interrupt_test_f411.bin', 'rx_interrupt_test_f411.bin'],
    ['rx_interrupt_test_f429', 'firmware/rx_interrupt_test/rx_interrupt_test_f429.bin', 'rx_interrupt_test_f429.bin'],
    ['blink_serial', 'firmware/blink_serial/build/blink_serial.ino.bin', 'blink_serial.ino.bin'],
    ['timer_test', 'firmware/timer_test/build/timer_test.ino.bin', 'timer_test.ino.bin'],
    ['test_firmware', 'firmware/test_firmware/test_firmware.bin', 'test_firmware.bin'],
    ['arduino_test', 'firmware/arduino_test/arduino_test.ino.bin', 'arduino_test.ino.bin'],
    ['i2s_sai_test', 'firmware/i2s_sai_test/i2s_sai_test.bin', 'i2s_sai_test.bin'],
    ['spi_tft_test', 'firmware/spi_tft_test/spi_tft_test.bin', 'spi_tft_test.bin'],
    // audio + display
    ['audio_test', 'firmware/audio_test/audio_test.bin', 'audio_test.bin'],
    ['ltdc_test', 'firmware/ltdc_test/ltdc_test.bin', 'ltdc_test.bin'],
    ['fsmc_test', 'firmware/fsmc_test/fsmc_test.bin', 'fsmc_test.bin'],
    ['dcmi_test', 'firmware/dcmi_test/dcmi_test.bin', 'dcmi_test.bin'],
    // virtual devices (OLED / TFT / buzzer / speaker panels)
    ['oled_test', 'firmware/oled_test/oled_test.bin', 'oled_test.bin'],
    ['tft_test', 'firmware/tft_test/tft_test.bin', 'tft_test.bin'],
    ['buzzer_test', 'firmware/buzzer_test/buzzer_test.bin', 'buzzer_test.bin'],
    ['audio_play_test', 'firmware/audio_play_test/audio_play_test.bin', 'audio_play_test.bin'],
    ['rtc_test', 'firmware/rtc_test/rtc_test.bin', 'rtc_test.bin'],
    ['can_test', 'firmware/can_test/can_test.bin', 'can_test.bin'],
    ['can_demo', 'firmware/can_demo/can_demo.bin', 'can_demo.bin'],
    ['can_host_rx', 'firmware/can_host_rx/can_host_rx.bin', 'can_host_rx.bin'],
    ['watchdog_demo', 'firmware/watchdog_demo/watchdog_demo.bin', 'watchdog_demo.bin'],
    ['wwdg_demo', 'firmware/wwdg_demo/wwdg_demo.bin', 'wwdg_demo.bin'],
    ['wwdg_window_demo', 'firmware/wwdg_window_demo/wwdg_window_demo.bin', 'wwdg_window_demo.bin'],
    ['tim_capture_demo', 'firmware/tim_capture_demo/tim_capture_demo.bin', 'tim_capture_demo.bin'],
    ['deep_sleep_demo', 'firmware/deep_sleep_demo/deep_sleep_demo.bin', 'deep_sleep_demo.bin'],
    ['standby_demo', 'firmware/standby_demo/standby_demo.bin', 'standby_demo.bin'],
    // QSPI indirect read/write round-trip
    ['qspi_test', 'firmware/qspi_test/qspi_test.bin', 'qspi_test.bin'],
    // VFPv4-SP: real GCC hard-float (vfma/vcmpe/vcvt/vsqrt/D=1 regs)
    ['fpu_test', 'firmware/fpu_test/fpu_test.bin', 'fpu_test.bin'],
    ['fpu_irq_test', 'firmware/fpu_irq_test/fpu_irq_test.bin', 'fpu_irq_test.bin'],
    ['mpu_test', 'firmware/mpu_test/mpu_test.bin', 'mpu_test.bin'],
    // USB OTG FS device: CDC-ACM echo, enumerated by a harness host
    ['usb_cdc_test', 'firmware/usb_cdc_test/usb_cdc_test.bin', 'usb_cdc_test.bin'],
    // board-family builds (matrix-verified; see site/test_board_matrix.mjs)
    ['adc_demo_f401', 'firmware/adc_demo/adc_demo_f401.bin', 'adc_demo_f401.bin'],
    ['adc_demo_f411', 'firmware/adc_demo/adc_demo_f411.bin', 'adc_demo_f411.bin'],
    ['adc_demo_f429', 'firmware/adc_demo/adc_demo_f429.bin', 'adc_demo_f429.bin'],
    ['pwm_demo_f401', 'firmware/pwm_demo/pwm_demo_f401.bin', 'pwm_demo_f401.bin'],
    ['pwm_demo_f411', 'firmware/pwm_demo/pwm_demo_f411.bin', 'pwm_demo_f411.bin'],
    ['pwm_demo_f429', 'firmware/pwm_demo/pwm_demo_f429.bin', 'pwm_demo_f429.bin'],
    ['oled_test_f401', 'firmware/oled_test/oled_test_f401.bin', 'oled_test_f401.bin'],
    ['oled_test_f411', 'firmware/oled_test/oled_test_f411.bin', 'oled_test_f411.bin'],
    ['oled_test_f429', 'firmware/oled_test/oled_test_f429.bin', 'oled_test_f429.bin'],
    ['tft_test_f401', 'firmware/tft_test/tft_test_f401.bin', 'tft_test_f401.bin'],
    ['tft_test_f411', 'firmware/tft_test/tft_test_f411.bin', 'tft_test_f411.bin'],
    ['tft_test_f429', 'firmware/tft_test/tft_test_f429.bin', 'tft_test_f429.bin'],
    ['buzzer_test_f401', 'firmware/buzzer_test/buzzer_test_f401.bin', 'buzzer_test_f401.bin'],
    ['buzzer_test_f411', 'firmware/buzzer_test/buzzer_test_f411.bin', 'buzzer_test_f411.bin'],
    ['buzzer_test_f429', 'firmware/buzzer_test/buzzer_test_f429.bin', 'buzzer_test_f429.bin'],
    ['audio_play_test_f401', 'firmware/audio_play_test/audio_play_test_f401.bin', 'audio_play_test_f401.bin'],
    ['audio_play_test_f411', 'firmware/audio_play_test/audio_play_test_f411.bin', 'audio_play_test_f411.bin'],
    ['audio_play_test_f429', 'firmware/audio_play_test/audio_play_test_f429.bin', 'audio_play_test_f429.bin'],
    ['watchdog_demo_f401', 'firmware/watchdog_demo/watchdog_demo_f401.bin', 'watchdog_demo_f401.bin'],
    ['watchdog_demo_f411', 'firmware/watchdog_demo/watchdog_demo_f411.bin', 'watchdog_demo_f411.bin'],
    ['watchdog_demo_f429', 'firmware/watchdog_demo/watchdog_demo_f429.bin', 'watchdog_demo_f429.bin'],
    ['wwdg_demo_f401', 'firmware/wwdg_demo/wwdg_demo_f401.bin', 'wwdg_demo_f401.bin'],
    ['wwdg_demo_f411', 'firmware/wwdg_demo/wwdg_demo_f411.bin', 'wwdg_demo_f411.bin'],
    ['wwdg_demo_f429', 'firmware/wwdg_demo/wwdg_demo_f429.bin', 'wwdg_demo_f429.bin'],
    ['wwdg_window_demo_f401', 'firmware/wwdg_window_demo/wwdg_window_demo_f401.bin', 'wwdg_window_demo_f401.bin'],
    ['wwdg_window_demo_f411', 'firmware/wwdg_window_demo/wwdg_window_demo_f411.bin', 'wwdg_window_demo_f411.bin'],
    ['wwdg_window_demo_f429', 'firmware/wwdg_window_demo/wwdg_window_demo_f429.bin', 'wwdg_window_demo_f429.bin'],
    ['tim_capture_demo_f401', 'firmware/tim_capture_demo/tim_capture_demo_f401.bin', 'tim_capture_demo_f401.bin'],
    ['tim_capture_demo_f411', 'firmware/tim_capture_demo/tim_capture_demo_f411.bin', 'tim_capture_demo_f411.bin'],
    ['tim_capture_demo_f429', 'firmware/tim_capture_demo/tim_capture_demo_f429.bin', 'tim_capture_demo_f429.bin'],
    ['spi_flash_test_f401', 'firmware/spi_flash_test/spi_flash_test_f401.bin', 'spi_flash_test_f401.bin'],
    ['spi_flash_test_f411', 'firmware/spi_flash_test/spi_flash_test_f411.bin', 'spi_flash_test_f411.bin'],
    ['spi_flash_test_f429', 'firmware/spi_flash_test/spi_flash_test_f429.bin', 'spi_flash_test_f429.bin'],
    ['flash_test_f401', 'firmware/flash_test/flash_test_f401.bin', 'flash_test_f401.bin'],
    ['flash_test_f411', 'firmware/flash_test/flash_test_f411.bin', 'flash_test_f411.bin'],
    ['flash_test_f429', 'firmware/flash_test/flash_test_f429.bin', 'flash_test_f429.bin'],
    ['exti_test_f401', 'firmware/exti_test/exti_test_f401.bin', 'exti_test_f401.bin'],
    ['exti_test_f411', 'firmware/exti_test/exti_test_f411.bin', 'exti_test_f411.bin'],
    ['exti_test_f429', 'firmware/exti_test/exti_test_f429.bin', 'exti_test_f429.bin'],
    ['rx_crypto_test_f401', 'firmware/rx_crypto_test/rx_crypto_test_f401.bin', 'rx_crypto_test_f401.bin'],
    ['rx_crypto_test_f411', 'firmware/rx_crypto_test/rx_crypto_test_f411.bin', 'rx_crypto_test_f411.bin'],
    ['rx_crypto_test_f429', 'firmware/rx_crypto_test/rx_crypto_test_f429.bin', 'rx_crypto_test_f429.bin'],
    ['test_firmware_f401', 'firmware/test_firmware/test_firmware_f401.bin', 'test_firmware_f401.bin'],
    ['test_firmware_f411', 'firmware/test_firmware/test_firmware_f411.bin', 'test_firmware_f411.bin'],
    ['test_firmware_f429', 'firmware/test_firmware/test_firmware_f429.bin', 'test_firmware_f429.bin'],
    ['spi_tft_test_f401', 'firmware/spi_tft_test/spi_tft_test_f401.bin', 'spi_tft_test_f401.bin'],
    ['spi_tft_test_f411', 'firmware/spi_tft_test/spi_tft_test_f411.bin', 'spi_tft_test_f411.bin'],
    ['spi_tft_test_f429', 'firmware/spi_tft_test/spi_tft_test_f429.bin', 'spi_tft_test_f429.bin'],
    ['deep_sleep_demo_f401', 'firmware/deep_sleep_demo/deep_sleep_demo_f401.bin', 'deep_sleep_demo_f401.bin'],
    ['deep_sleep_demo_f411', 'firmware/deep_sleep_demo/deep_sleep_demo_f411.bin', 'deep_sleep_demo_f411.bin'],
    ['deep_sleep_demo_f429', 'firmware/deep_sleep_demo/deep_sleep_demo_f429.bin', 'deep_sleep_demo_f429.bin'],
    ['standby_demo_f401', 'firmware/standby_demo/standby_demo_f401.bin', 'standby_demo_f401.bin'],
    ['standby_demo_f411', 'firmware/standby_demo/standby_demo_f411.bin', 'standby_demo_f411.bin'],
    ['standby_demo_f429', 'firmware/standby_demo/standby_demo_f429.bin', 'standby_demo_f429.bin'],
    ['rtc_test_f401', 'firmware/rtc_test/rtc_test_f401.bin', 'rtc_test_f401.bin'],
    ['rtc_test_f411', 'firmware/rtc_test/rtc_test_f411.bin', 'rtc_test_f411.bin'],
    ['rtc_test_f429', 'firmware/rtc_test/rtc_test_f429.bin', 'rtc_test_f429.bin'],
    ['audio_test_f401', 'firmware/audio_test/audio_test_f401.bin', 'audio_test_f401.bin'],
    ['audio_test_f411', 'firmware/audio_test/audio_test_f411.bin', 'audio_test_f411.bin'],
    ['audio_test_f429', 'firmware/audio_test/audio_test_f429.bin', 'audio_test_f429.bin'],
    ['fpu_test_f401', 'firmware/fpu_test/fpu_test_f401.bin', 'fpu_test_f401.bin'],
    ['fpu_test_f411', 'firmware/fpu_test/fpu_test_f411.bin', 'fpu_test_f411.bin'],
    ['fpu_test_f429', 'firmware/fpu_test/fpu_test_f429.bin', 'fpu_test_f429.bin'],
    ['fpu_irq_test_f401', 'firmware/fpu_irq_test/fpu_irq_test_f401.bin', 'fpu_irq_test_f401.bin'],
    ['fpu_irq_test_f411', 'firmware/fpu_irq_test/fpu_irq_test_f411.bin', 'fpu_irq_test_f411.bin'],
    ['fpu_irq_test_f429', 'firmware/fpu_irq_test/fpu_irq_test_f429.bin', 'fpu_irq_test_f429.bin'],
    ['mpu_test_f401', 'firmware/mpu_test/mpu_test_f401.bin', 'mpu_test_f401.bin'],
    ['mpu_test_f411', 'firmware/mpu_test/mpu_test_f411.bin', 'mpu_test_f411.bin'],
    ['mpu_test_f429', 'firmware/mpu_test/mpu_test_f429.bin', 'mpu_test_f429.bin'],
    ['freertos_test_f411', 'firmware/freertos_test/freertos_test_f411.bin', 'freertos_test_f411.bin'],
    ['freertos_test_f429', 'firmware/freertos_test/freertos_test_f429.bin', 'freertos_test_f429.bin'],
    ['can_demo_f429', 'firmware/can_demo/can_demo_f429.bin', 'can_demo_f429.bin'],
    ['can_test_f429', 'firmware/can_test/can_test_f429.bin', 'can_test_f429.bin'],
    ['can_host_rx_f429', 'firmware/can_host_rx/can_host_rx_f429.bin', 'can_host_rx_f429.bin'],
    ['dac_demo_f429', 'firmware/dac_demo/dac_demo_f429.bin', 'dac_demo_f429.bin'],
    ['fsmc_test_f429', 'firmware/fsmc_test/fsmc_test_f429.bin', 'fsmc_test_f429.bin'],
    ['dcmi_test_f429', 'firmware/dcmi_test/dcmi_test_f429.bin', 'dcmi_test_f429.bin'],
    ['qspi_test_f429', 'firmware/qspi_test/qspi_test_f429.bin', 'qspi_test_f429.bin'],
    ['gap10_sdio', 'firmware/gap10_sdio/gap10_sdio.bin', 'gap10_sdio.bin'],
    ['gap10_qspi', 'firmware/gap10_qspi/gap10_qspi.bin', 'gap10_qspi.bin'],
    ['gap10_ltdc', 'firmware/gap10_ltdc/gap10_ltdc.bin', 'gap10_ltdc.bin'],
    ['gap10_i2c', 'firmware/gap10_i2c/gap10_i2c.bin', 'gap10_i2c.bin'],
    ['gap10_dma', 'firmware/gap10_dma/gap10_dma.bin', 'gap10_dma.bin'],
    ['gap10_dac', 'firmware/gap10_dac/gap10_dac.bin', 'gap10_dac.bin'],
    ['ltdc_test_f429', 'firmware/ltdc_test/ltdc_test_f429.bin', 'ltdc_test_f429.bin'],
    ['crypto_deep_test_f429', 'firmware/crypto_deep_test/crypto_deep_test_f429.bin', 'crypto_deep_test_f429.bin'],
    ['i2s_sai_test_f429', 'firmware/i2s_sai_test/i2s_sai_test_f429.bin', 'i2s_sai_test_f429.bin'],
    ['usb_cdc_test_f401', 'firmware/usb_cdc_test/usb_cdc_test_f401.bin', 'usb_cdc_test_f401.bin'],
    ['usb_cdc_test_f429', 'firmware/usb_cdc_test/usb_cdc_test_f429.bin', 'usb_cdc_test_f429.bin'],
    ['hal_test_bp_f401cc', 'firmware/hal_test/build-bp_f401cc/hal_test.ino.bin', 'hal_test_bp_f401cc.bin'],
    ['hal_test_bp_f411ce', 'firmware/hal_test/build-bp_f411ce/hal_test.ino.bin', 'hal_test_bp_f411ce.bin'],
    ['hal_test_nucleo_f401re', 'firmware/hal_test/build-nucleo_f401re/hal_test.ino.bin', 'hal_test_nucleo_f401re.bin'],
    ['hal_test_nucleo_f411re', 'firmware/hal_test/build-nucleo_f411re/hal_test.ino.bin', 'hal_test_nucleo_f411re.bin'],
    ['hal_test_disco_f407vg', 'firmware/hal_test/build-disco_f407vg/hal_test.ino.bin', 'hal_test_disco_f407vg.bin'],
    ['hal_test_disco_f429zi', 'firmware/hal_test/build-disco_f429zi/hal_test.ino.bin', 'hal_test_disco_f429zi.bin'],
    ['hal_test_black_f407ve', 'firmware/hal_test/build-black_f407ve/hal_test.ino.bin', 'hal_test_black_f407ve.bin'],
    ['hal_test_black_f407ze', 'firmware/hal_test/build-black_f407ze/hal_test.ino.bin', 'hal_test_black_f407ze.bin'],
    ['arduino_test_bp_f401cc', 'firmware/arduino_test/build-bp_f401cc/arduino_test.ino.bin', 'arduino_test_bp_f401cc.bin'],
    ['arduino_test_bp_f411ce', 'firmware/arduino_test/build-bp_f411ce/arduino_test.ino.bin', 'arduino_test_bp_f411ce.bin'],
    ['arduino_test_nucleo_f401re', 'firmware/arduino_test/build-nucleo_f401re/arduino_test.ino.bin', 'arduino_test_nucleo_f401re.bin'],
    ['arduino_test_nucleo_f411re', 'firmware/arduino_test/build-nucleo_f411re/arduino_test.ino.bin', 'arduino_test_nucleo_f411re.bin'],
    ['arduino_test_disco_f407vg', 'firmware/arduino_test/build-disco_f407vg/arduino_test.ino.bin', 'arduino_test_disco_f407vg.bin'],
    ['arduino_test_disco_f429zi', 'firmware/arduino_test/build-disco_f429zi/arduino_test.ino.bin', 'arduino_test_disco_f429zi.bin'],
    ['arduino_test_black_f407ve', 'firmware/arduino_test/build-black_f407ve/arduino_test.ino.bin', 'arduino_test_black_f407ve.bin'],
    ['arduino_test_black_f407ze', 'firmware/arduino_test/build-black_f407ze/arduino_test.ino.bin', 'arduino_test_black_f407ze.bin'],
    ['edge_test_bp_f401cc', 'firmware/edge_test/build-bp_f401cc/edge_test.ino.bin', 'edge_test_bp_f401cc.bin'],
    ['edge_test_bp_f411ce', 'firmware/edge_test/build-bp_f411ce/edge_test.ino.bin', 'edge_test_bp_f411ce.bin'],
    ['edge_test_nucleo_f401re', 'firmware/edge_test/build-nucleo_f401re/edge_test.ino.bin', 'edge_test_nucleo_f401re.bin'],
    ['edge_test_nucleo_f411re', 'firmware/edge_test/build-nucleo_f411re/edge_test.ino.bin', 'edge_test_nucleo_f411re.bin'],
    ['edge_test_disco_f407vg', 'firmware/edge_test/build-disco_f407vg/edge_test.ino.bin', 'edge_test_disco_f407vg.bin'],
    ['edge_test_disco_f429zi', 'firmware/edge_test/build-disco_f429zi/edge_test.ino.bin', 'edge_test_disco_f429zi.bin'],
    ['edge_test_black_f407ve', 'firmware/edge_test/build-black_f407ve/edge_test.ino.bin', 'edge_test_black_f407ve.bin'],
    ['edge_test_black_f407ze', 'firmware/edge_test/build-black_f407ze/edge_test.ino.bin', 'edge_test_black_f407ze.bin'],
    ['periph_test_bp_f401cc', 'firmware/periph_test/build-bp_f401cc/periph_test.ino.bin', 'periph_test_bp_f401cc.bin'],
    ['periph_test_bp_f411ce', 'firmware/periph_test/build-bp_f411ce/periph_test.ino.bin', 'periph_test_bp_f411ce.bin'],
    ['periph_test_nucleo_f401re', 'firmware/periph_test/build-nucleo_f401re/periph_test.ino.bin', 'periph_test_nucleo_f401re.bin'],
    ['periph_test_nucleo_f411re', 'firmware/periph_test/build-nucleo_f411re/periph_test.ino.bin', 'periph_test_nucleo_f411re.bin'],
    ['periph_test_disco_f407vg', 'firmware/periph_test/build-disco_f407vg/periph_test.ino.bin', 'periph_test_disco_f407vg.bin'],
    ['periph_test_disco_f429zi', 'firmware/periph_test/build-disco_f429zi/periph_test.ino.bin', 'periph_test_disco_f429zi.bin'],
    ['periph_test_black_f407ve', 'firmware/periph_test/build-black_f407ve/periph_test.ino.bin', 'periph_test_black_f407ve.bin'],
    ['periph_test_black_f407ze', 'firmware/periph_test/build-black_f407ze/periph_test.ino.bin', 'periph_test_black_f407ze.bin'],
    ['timer_test_disco_f407vg', 'firmware/timer_test/build-disco_f407vg/timer_test.ino.bin', 'timer_test_disco_f407vg.bin'],
    ['timer_test_disco_f429zi', 'firmware/timer_test/build-disco_f429zi/timer_test.ino.bin', 'timer_test_disco_f429zi.bin'],
    ['timer_test_black_f407ve', 'firmware/timer_test/build-black_f407ve/timer_test.ino.bin', 'timer_test_black_f407ve.bin'],
    ['timer_test_black_f407ze', 'firmware/timer_test/build-black_f407ze/timer_test.ino.bin', 'timer_test_black_f407ze.bin'],
    ['echo_test_disco_f407vg', 'firmware/echo_test/build-disco_f407vg/echo_test.ino.bin', 'echo_test_disco_f407vg.bin'],
    ['echo_test_disco_f429zi', 'firmware/echo_test/build-disco_f429zi/echo_test.ino.bin', 'echo_test_disco_f429zi.bin'],
    ['echo_test_black_f407ve', 'firmware/echo_test/build-black_f407ve/echo_test.ino.bin', 'echo_test_black_f407ve.bin'],
    ['echo_test_black_f407ze', 'firmware/echo_test/build-black_f407ze/echo_test.ino.bin', 'echo_test_black_f407ze.bin'],
    ['crypto_test_disco_f407vg', 'firmware/crypto_test/build-disco_f407vg/crypto_test.ino.bin', 'crypto_test_disco_f407vg.bin'],
    ['crypto_test_disco_f429zi', 'firmware/crypto_test/build-disco_f429zi/crypto_test.ino.bin', 'crypto_test_disco_f429zi.bin'],
    ['crypto_test_black_f407ve', 'firmware/crypto_test/build-black_f407ve/crypto_test.ino.bin', 'crypto_test_black_f407ve.bin'],
    ['crypto_test_black_f407ze', 'firmware/crypto_test/build-black_f407ze/crypto_test.ino.bin', 'crypto_test_black_f407ze.bin'],
    ['blink_serial_disco_f429zi', 'firmware/blink_serial/build-disco_f429zi/blink_serial.ino.bin', 'blink_serial_disco_f429zi.bin'],
    ['comprehensive_test_f429', 'firmware/comprehensive_test/comprehensive_test_f429.bin', 'comprehensive_test_f429.bin'],
    ['dma2d_test', 'firmware/dma2d_test/dma2d_test.bin', 'dma2d_test.bin'],
    ['dma2d_test_f429', 'firmware/dma2d_test/dma2d_test_f429.bin', 'dma2d_test_f429.bin'],
    ['gpio_k_test', 'firmware/gpio_k_test/gpio_k_test.bin', 'gpio_k_test.bin'],
    ['gpio_k_test_f429', 'firmware/gpio_k_test/gpio_k_test_f429.bin', 'gpio_k_test_f429.bin'],
    ['eth_pins_test', 'firmware/eth_pins_test/eth_pins_test.bin', 'eth_pins_test.bin'],
    ['eth_pins_test_f429', 'firmware/eth_pins_test/eth_pins_test_f429.bin', 'eth_pins_test_f429.bin'],
    ['dma2d_test_f429', 'firmware/dma2d_test/dma2d_test_f429.bin', 'dma2d_test_f429.bin'],
    // doom (doomgeneric F407 port; needs doom1.wad served alongside)
    ['doom', 'firmware/doom/doom.bin', 'doom.bin'],
];

const lines = [
    '// Generated by tools/make_firmware.mjs — do not edit',
    '// Embedded firmware binaries for the in-browser demo.',
    'export const FIRMWARES = {',
];
for (const [key, path, name] of firmwares) {
    const bytes = readFileSync(root + path);
    lines.push(`  ${key}: { name: ${JSON.stringify(name)}, bytes: ${JSON.stringify(bytes.toString('base64'))} },`);
}
lines.push('};');
writeFileSync(root + 'site/firmware.js', lines.join('\n') + '\n');
console.log('wrote site/firmware.js (' + firmwares.length + ' firmwares)');
