// Regenerates site/firmware.js from the built firmware binaries.
// Usage: node tools/make_firmware.mjs
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';

const root = fileURLToPath(new URL('..', import.meta.url));
const firmwares = [
    // network
    ['eth_http', 'eth_http/eth_http.bin', 'eth_http.bin'],
    ['eth_dhcp', 'eth_dhcp/eth_dhcp.bin', 'eth_dhcp.bin'],
    ['eth_test', 'eth_test/eth_test.bin', 'eth_test.bin'],
    // bare-metal demos
    ['blinky', 'blinky/blinky.bin', 'blinky.bin'],
    // test binaries (boot + print on UART; see site/probe_firmwares.mjs)
    ['hal_test', 'hal_test/hal_test.ino.bin', 'hal_test.ino.bin'],
    ['crypto_test', 'crypto_test/build/crypto_test.ino.bin', 'crypto_test.ino.bin'],
    ['crypto_deep_test', 'crypto_deep_test/crypto_deep_test.bin', 'crypto_deep_test.bin'],
    ['rx_crypto_test', 'rx_crypto_test/rx_crypto_test.bin', 'rx_crypto_test.bin'],
    ['periph_test', 'periph_test/periph_test.ino.bin', 'periph_test.ino.bin'],
    ['new_periph_test', 'new_periph_test/new_periph_test.ino.bin', 'new_periph_test.ino.bin'],
    ['deep_periph_test', 'deep_periph_test/build/deep_periph_test.ino.bin', 'deep_periph_test.ino.bin'],
    ['comprehensive_test', 'comprehensive_test/comprehensive_test.bin', 'comprehensive_test.bin'],
    ['eth_irq_test', 'eth_irq_test/eth_irq_test.bin', 'eth_irq_test.bin'],
    ['edge_test', 'edge_test/edge_test.ino.bin', 'edge_test.ino.bin'],
    ['echo_test', 'echo_test/build/echo_test.ino.bin', 'echo_test.ino.bin'],
    ['rx_interrupt_test', 'rx_interrupt_test/build/rx_interrupt_test.ino.bin', 'rx_interrupt_test.ino.bin'],
    ['blink_serial', 'blink_serial/build/blink_serial.ino.bin', 'blink_serial.ino.bin'],
    ['timer_test', 'timer_test/build/timer_test.ino.bin', 'timer_test.ino.bin'],
    ['test_firmware', 'test_firmware/test_firmware.bin', 'test_firmware.bin'],
    ['arduino_test', 'arduino_test/arduino_test.ino.bin', 'arduino_test.ino.bin'],
    ['i2s_sai_test', 'i2s_sai_test/i2s_sai_test.bin', 'i2s_sai_test.bin'],
    ['spi_tft_test', 'spi_tft_test/spi_tft_test.bin', 'spi_tft_test.bin'],
    // audio + display
    ['audio_test', 'audio_test/audio_test.bin', 'audio_test.bin'],
    ['ltdc_test', 'ltdc_test/ltdc_test.bin', 'ltdc_test.bin'],
    ['fsmc_test', 'fsmc_test/fsmc_test.bin', 'fsmc_test.bin'],
    ['dcmi_test', 'dcmi_test/dcmi_test.bin', 'dcmi_test.bin'],
    // virtual devices (OLED / TFT / buzzer / speaker panels)
    ['oled_test', 'oled_test/oled_test.bin', 'oled_test.bin'],
    ['tft_test', 'tft_test/tft_test.bin', 'tft_test.bin'],
    ['buzzer_test', 'buzzer_test/buzzer_test.bin', 'buzzer_test.bin'],
    ['audio_play_test', 'audio_play_test/audio_play_test.bin', 'audio_play_test.bin'],
    ['rtc_test', 'rtc_test/rtc_test.bin', 'rtc_test.bin'],
    ['can_test', 'can_test/can_test.bin', 'can_test.bin'],
    ['can_demo', 'can_demo/can_demo.bin', 'can_demo.bin'],
    ['can_host_rx', 'can_host_rx/can_host_rx.bin', 'can_host_rx.bin'],
    ['watchdog_demo', 'watchdog_demo/watchdog_demo.bin', 'watchdog_demo.bin'],
    ['wwdg_demo', 'wwdg_demo/wwdg_demo.bin', 'wwdg_demo.bin'],
    ['wwdg_window_demo', 'wwdg_window_demo/wwdg_window_demo.bin', 'wwdg_window_demo.bin'],
    ['tim_capture_demo', 'tim_capture_demo/tim_capture_demo.bin', 'tim_capture_demo.bin'],
    ['deep_sleep_demo', 'deep_sleep_demo/deep_sleep_demo.bin', 'deep_sleep_demo.bin'],
    // doom (doomgeneric F407 port; needs doom1.wad served alongside)
    ['doom', 'doom/doom.bin', 'doom.bin'],
];

const lines = [
    '// Generated by tools/make_firmware.mjs — do not edit',
    '// Embedded firmware binaries for the in-browser demo.',
    'export const FIRMWARES = {',
];
for (const [key, path, name] of firmwares) {
    const bytes = readFileSync(root + path);
    lines.push(`  ${key}: { name: ${JSON.stringify(name)}, bytes: ${JSON.stringify(bytes.toString('base64'))} },`);
}
lines.push('};');
writeFileSync(root + 'site/firmware.js', lines.join('\n') + '\n');
console.log('wrote site/firmware.js (' + firmwares.length + ' firmwares)');
